# Generated by Django 3.2.3 on 2021-07-07 20:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='id',
        ),
        migrations.RemoveField(
            model_name='services',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='id',
        ),
        migrations.AlterField(
            model_name='plans',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='services',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
