# Generated by Django 3.2.3 on 2021-07-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_servicesplans'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='plans',
            field=models.ManyToManyField(blank=True, through='plans.ServicesPlans', to='plans.Plan'),
        ),
    ]
