# Generated by Django 3.2.3 on 2021-08-02 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_auto_20210728_1622'),
        ('plans', '0006_service_plans'),
    ]

    operations = [
    ]
