# Generated by Django 3.2.3 on 2021-08-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_merge_0006_auto_20210728_1622_0006_service_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesplans',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
