# Generated by Django 3.2.3 on 2021-09-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_alter_servicesplans_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='cgst',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='sgst',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
