# Generated by Django 3.2.3 on 2021-09-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_auto_20210920_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
