# Generated by Django 3.2.3 on 2021-10-02 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0013_alter_plan_check_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=512, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanPlatformComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plans.plan')),
                ('platform_components', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='plans.platformcomponents')),
            ],
            options={
                'unique_together': {('plan', 'platform_components')},
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='platform_components',
            field=models.ManyToManyField(through='plans.PlanPlatformComponents', to='plans.PlatformComponents'),
        ),
    ]
