# Generated by Django 3.2.3 on 2021-10-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0014_auto_20211002_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Free Plan'), (2, 'Calling Plan'), (3, 'Premium Plan')], default=1),
        ),
    ]
