# Generated by Django 3.2.3 on 2021-05-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_source', models.PositiveSmallIntegerField(choices=[(1, 'WEB'), (2, 'SALES'), (3, 'SOCIAL')])),
                ('resolution', models.PositiveSmallIntegerField(choices=[(1, 'CONVERTED'), (2, 'DROPPED')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.BigIntegerField(unique=True, verbose_name='Phone Number')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
