# Generated by Django 3.2.3 on 2021-05-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_rename_customerleads_customerlead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlead',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customerlead',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='customerlead',
            name='lead_source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'WEB'), (2, 'SALES'), (3, 'SOCIAL')], verbose_name='Lead Source'),
        ),
        migrations.AlterField(
            model_name='customerlead',
            name='phone_number',
            field=models.BigIntegerField(default=None, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customerlead',
            name='resolution',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CONVERTED'), (2, 'DROPPED')], verbose_name='Resolution'),
        ),
    ]
