# Generated by Django 3.2.3 on 2021-05-28 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_customerlead_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerlead',
            table='customer_lead',
        ),
    ]
