# Generated by Django 3.2.3 on 2021-05-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_customerlead_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlead',
            name='resolution',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CONVERTED'), (2, 'DROPPED')], null=True, verbose_name='Resolution'),
        ),
    ]
