# Generated by Django 3.2.3 on 2021-05-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_alter_customerlead_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlead',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
