# Generated by Django 3.2.3 on 2021-06-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_customerlead_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlead',
            name='resolution',
            field=models.PositiveSmallIntegerField(choices=[(1, 'IN PROGRESS'), (2, 'CONVERTED'), (3, 'DROPPED')], default=1, null=True, verbose_name='Resolution'),
        ),
    ]
