# Generated by Django 3.2.3 on 2021-10-22 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0009_auto_20210921_1515'),
        ('chats', '0002_auto_20210719_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='case_chats_receipts', to='cases.case')),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_receipts', to='chats.chat')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_chat_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
