# Generated by Django 3.2.3 on 2021-08-10 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('numeric_code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('phone_code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('capital', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('currency_symbol', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('city_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='country', to='Core.country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
