# Generated by Django 3.2.3 on 2021-08-11 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-created_at']},
        ),
    ]
