# Generated by Django 3.2.3 on 2021-08-11 12:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20210811_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 8, 11, 12, 20, 4, 651626, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
