# Generated by Django 3.2.3 on 2021-08-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_auto_20210811_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-id']},
        ),
    ]
