# Generated by Django 3.2.3 on 2021-12-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_triggeredemails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triggeredemails',
            name='user',
        ),
    ]
