# Generated by Django 3.2.3 on 2021-08-04 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call_schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendlyusers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='calendly_details', to=settings.AUTH_USER_MODEL, verbose_name='RCIC or account manager user'),
        ),
        migrations.CreateModel(
            name='CalendlyCallSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_event_invitee_url', models.CharField(max_length=1024)),
                ('cancel_call_url', models.CharField(max_length=1024, null=True)),
                ('reschedule_call_url', models.CharField(max_length=1024, null=True)),
                ('communication_means', models.JSONField(verbose_name='Stores communication means details from Calendly')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Rescheduled'), (3, 'Canceled')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('call_schedule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='calendly_schedule_details', to='call_schedule.callschedule')),
            ],
            options={
                'db_table': 'calendly_call_schedule',
            },
        ),
    ]
