# Generated by Django 3.2.3 on 2021-08-07 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendlyInviteeScheduleUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('schedule_url', models.CharField(max_length=1024, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='calendly_invitee_sch_url', to=settings.AUTH_USER_MODEL, verbose_name='RCIC or Account Manager')),
                ('invitee_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='calendly_schedule_url', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'db_table': 'calendly_invitee_schedule_url',
            },
        ),
    ]
