# Generated by Django 3.2.3 on 2021-08-07 07:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendly', '0002_calendlyinviteescheduleurl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalendlyInviteeScheduleUrl',
            new_name='CalendlyInviteeScheduledUrl',
        ),
        migrations.RenameField(
            model_name='calendlycallschedule',
            old_name='cancel_call_url',
            new_name='cancel_url',
        ),
        migrations.RenameField(
            model_name='calendlycallschedule',
            old_name='scheduled_event_invitee_url',
            new_name='invitee_url',
        ),
        migrations.RenameField(
            model_name='calendlycallschedule',
            old_name='reschedule_call_url',
            new_name='reschedule_url',
        ),
        migrations.RenameField(
            model_name='calendlyinviteescheduledurl',
            old_name='schedule_url',
            new_name='scheduled_call_url',
        ),
        migrations.RenameField(
            model_name='calendlyusers',
            old_name='event_type_resource_url',
            new_name='event_type_url',
        ),
        migrations.RenameField(
            model_name='calendlyusers',
            old_name='user_resource_url',
            new_name='user_url',
        ),
    ]
