# Generated by Django 3.2.3 on 2021-08-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendly', '0003_auto_20210807_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendlycallschedule',
            name='invitee_url',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
