FROM python:3.8-slim-buster

RUN apt-get update
RUN apt-get -y install gcc

WORKDIR /rest/BackendApp

COPY ./requirements/base.txt ./

# Prevents Python from writing pyc files to disc
ENV PYTHONDONTWRITEBYTECODE 1

# Prevents Python from buffering stdout and stderr
ENV PYTHONUNBUFFERED 1

COPY ./docker-build/wsgi-entry.sh /rest/

RUN chmod +x /rest/wsgi-entry.sh 

RUN apt-get install -y --no-install-recommends python-dev libpq-dev

RUN mkdir -p /rest/logs && \
    pip3 install wheel==0.34.2 && \
    pip3 install -r base.txt 

COPY ./ ./

CMD [ "python", "manage.py",  "migrate"]

#CMD [ "python", "manage.py",  "runserver", "0.0.0.0:8000" ]

#ENTRYPOINT ["/rest/wsgi-entry.sh"]
