FROM python:3.8-slim-buster

RUN apt-get update && \
	apt-get -y install gcc && \
	python3 -m pip install --upgrade pip

WORKDIR /rest/BackendApp

COPY ./requirements/base.txt ./

# default value
ARG req_file=requirements/local.txt

COPY $req_file ./requirements.txt

# Prevents Python from writing pyc files to disc
ENV PYTHONDONTWRITEBYTECODE 1

# Prevents Python from buffering stdout and stderr
ENV PYTHONUNBUFFERED 1

#default value
ARG django_settings_value=config.settings.local 

ENV DJANGO_SETTINGS_MODULE=$django_settings_value

COPY ./docker-build/wsgi-entry.sh /rest/

RUN chmod +x /rest/wsgi-entry.sh 

RUN apt-get install -y --no-install-recommends python-dev libpq-dev

RUN mkdir -p /rest/logs && \
    pip3 install wheel==0.34.2 && \
    pip3 install -r base.txt 

COPY ./ ./

CMD [ "python", "manage.py",  "migrate"]

#CMD [ "python", "manage.py",  "runserver", "0.0.0.0:8000" ]

#ENTRYPOINT ["/rest/wsgi-entry.sh"]
