# Generated by Django 3.2.3 on 2022-06-21 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('date_of_birth', models.DateField(default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('start_year', models.DateField(blank=True, default=None, null=True)),
                ('end_year', models.DateField(blank=True, default=None, null=True)),
                ('name_of_institue', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('course_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('score', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('student_profile', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='study.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
