# Generated by Django 3.2.3 on 2022-06-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfileLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user_label', models.CharField(default='user', max_length=10)),
                ('first_name_label', models.CharField(max_length=10)),
                ('last_name_label', models.CharField(max_length=10)),
                ('nationality_label', models.CharField(max_length=10)),
                ('date_of_birth_label', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QualificationLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user_label', models.CharField(default='user', max_length=512)),
                ('start_year_label', models.CharField(max_length=512)),
                ('end_year_label', models.CharField(max_length=512)),
                ('name_of_institute_label', models.CharField(max_length=512)),
                ('course_name_label', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('score_label', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
