LOGGER_LOG_MESSAGE="MESSAGE"
LOGGER_LOW_SEVERITY = "LOW"
LOGGER_MODERATE_SEVERITY = "MODERATE"
LOGGER_CRITICAL_SEVERITY = "CRITICAL"

GENERIC_ERROR = "Server Failed to Complete request. Please try again later"

