# Generated by Django 3.2.3 on 2021-05-31 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0007_alter_customerlead_resolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(null=True, verbose_name='Data')),
                ('lead_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lead_id', to='leads.customerlead')),
            ],
            options={
                'db_table': 'eligibility_results',
            },
        ),
    ]
