# Generated by Django 3.2.3 on 2021-06-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_calculator', '0002_auto_20210603_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilityresults',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eligibilityresults',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
