# Generated by Django 3.2.3 on 2022-03-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_homeleads_websitecontactdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeleads',
            name='leadsquared_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homeleads',
            name='leadsquared_status_code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='websitecontactdata',
            name='leadsquared_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='websitecontactdata',
            name='leadsquared_status_code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
