# Generated by Django 3.2.3 on 2022-04-04 11:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_homeleads_websitecontactdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('body', ckeditor.fields.RichTextField()),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('component_name', models.PositiveSmallIntegerField(choices=[(1, 'Contact Us'), (2, 'Home'), (3, 'Testimonials')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
