# Generated by Django 3.2.3 on 2022-04-25 05:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_websitecomponents'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('body', ckeditor.fields.RichTextField()),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
