# Generated by Django 3.2.3 on 2022-05-27 07:44

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_websitecomponents_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecomponents',
            name='blog_img',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='blog', verbose_name='Blog Image'),
        ),
    ]
