# Generated by Django 3.2.3 on 2022-05-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_websitecomponents_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecomponents',
            name='blog_img',
            field=models.FileField(blank=True, upload_to='blog', verbose_name='Blog Image'),
        ),
    ]
