# Generated by Django 3.2.3 on 2023-01-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_websitecomponents_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecomponents',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
    ]
