# Generated by Django 3.2.3 on 2023-01-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_websitecomponents_highlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='IeltsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default=None, max_length=100)),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('exam_type', models.PositiveSmallIntegerField(choices=[(1, 'Academic'), (2, 'General')])),
                ('module', models.PositiveSmallIntegerField(choices=[(1, 'Reading'), (2, 'Writing'), (3, 'Speaking'), (4, 'Listening'), (5, 'All modules')])),
                ('ielts_img', models.FileField(blank=True, upload_to='ielts', verbose_name='Ielts Image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
