# Generated by Django 3.2.3 on 2023-01-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_jobpostingdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostingdata',
            name='description',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='jobpostingdata',
            name='experience',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
