# Generated by Django 3.2.3 on 2021-07-22 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0002_auto_20210708_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('q_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('account_manager_id', models.IntegerField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Accpeted'), (2, 'Rejected')], default=1, verbose_name='quo_status')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plan_quotations', to='plans.plan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_quotaions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuotationMilestone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('qm_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Paid'), (2, 'Unpaid')], default=2, verbose_name='quo_milestone_status')),
                ('description', models.TextField(blank=True, null=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='milestones_quote', to='quotations.quotation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
