# Generated by Django 3.2.3 on 2021-08-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_auto_20210728_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CREATED'), (2, 'ACCEPTED'), (3, 'REJECTED')], default=1, verbose_name='quo_status'),
        ),
    ]
