# Generated by Django 3.2.3 on 2021-09-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_client_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Stripe')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Cancelled')], default=1),
        ),
    ]
