# Generated by Django 3.2.3 on 2021-09-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_transaction_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_clients_unique_id',
            new_name='frontend_payment_clients_unique_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='webhook_payment_clients_unique_id',
            field=models.CharField(default='', max_length=1024, unique=True),
            preserve_default=False,
        ),
    ]
