# Generated by Django 3.2.3 on 2022-04-18 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_razorpaytransactions_userorderdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razorpaytransactions',
            name='user',
        ),
        migrations.AddField(
            model_name='razorpaytransactions',
            name='user_order_details',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_razorpay_transactions', to='payment.userorderdetails'),
            preserve_default=False,
        ),
    ]
