# Generated by Django 3.2.3 on 2022-04-19 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_razorpaytransactions_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpaytransactions',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_razorpay_transactions', to='payment.order'),
        ),
    ]
