# Generated by Django 3.2.3 on 2022-04-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_alter_razorpaytransactions_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razorpaytransactions',
            name='order_id',
        ),
    ]
