# Generated by Django 3.2.3 on 2022-04-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_remove_razorpaytransactions_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpaytransactions',
            name='currency',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
