# Generated by Django 3.2.3 on 2022-04-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_razorpaytransactions_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='razorpaytransactions',
            old_name='order_payment_id',
            new_name='order_id',
        ),
        migrations.AddField(
            model_name='razorpaytransactions',
            name='payment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
