# Generated by Django 3.2.3 on 2022-04-26 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0015_plan_type'),
        ('payment', '0016_auto_20220421_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razorpaytransactions',
            name='plan_id',
        ),
        migrations.AddField(
            model_name='userorderdetails',
            name='plan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plans.plan'),
        ),
    ]
