# Generated by Django 3.2.3 on 2022-04-29 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_auto_20220428_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_client_type',
        ),
    ]
