# Generated by Django 3.2.3 on 2021-07-07 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_alter_task_check_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='case_id',
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('case_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('account_manager_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='agents_cases', to=settings.AUTH_USER_MODEL)),
                ('ref_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='users_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='task',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cases_tasks', to='tasks.case'),
        ),
    ]
