# Generated by Django 3.2.3 on 2021-07-08 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('tasks', '0004_auto_20210707_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cases_tasks', to='cases.case'),
        ),
        migrations.DeleteModel(
            name='Case',
        ),
    ]
