# Generated by Django 3.2.3 on 2021-09-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20210719_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'In Review'), (2, 'Completed')], default=0),
        ),
    ]
