# Generated by Django 3.2.3 on 2021-12-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_template',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
