# Generated by Django 3.2.3 on 2022-01-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_is_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
