# Generated by Django 3.2.3 on 2022-01-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_tasktemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='priority',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
