FROM nginx:1.19.0-alpine

RUN pwd

RUN ls -a

WORKDIR /etc/nginx/conf.d/

RUN ls -a

#COPY ./docker-build/nginx.conf /etc/nginx/nginx.conf

#COPY ./docker-build/default.conf /etc/nginx/conf.d/default.conf

RUN rm /etc/nginx/conf.d/default.conf
COPY ./docker-build/nginx.conf /etc/nginx/conf.d

