# Generated by Django 3.2.3 on 2021-06-29 14:08

import django.core.files.storage
from django.db import migrations, models
import keel.document.utils


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='avatar',
            field=models.FileField(blank=True, upload_to=keel.document.utils.upload_files_to, verbose_name='Documents'),
        ),
    ]
