# Generated by Django 3.2.3 on 2021-07-12 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_documenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='new_doc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doc_type_docs', to='document.documenttype'),
        ),
    ]
