# Generated by Django 3.2.3 on 2021-07-12 18:01

from django.db import migrations

def pre_fill_doc_type(apps, schema_editor):

    DEFAULT_PK_ID = 1
    DocType = apps.get_model('document', 'DocumentType')
    doc_type, created = DocType.objects.get_or_create(id = DEFAULT_PK_ID, doc_type_name = 'Others', description = '')
    if created:
        Doc = apps.get_model('document', 'Documents')
        for doc in Doc.objects.all():
            doc.new_doc_type = doc_type
            doc.save()

class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_documents_new_doc_type'),
    ]

    operations = [ migrations.RunPython(pre_fill_doc_type),
    ]
