# Generated by Django 3.2.3 on 2021-07-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_auto_20210712_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='doc_type',
        ),
    ]
