# Generated by Django 3.2.3 on 2021-07-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_remove_documents_doc_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='new_doc_type',
            new_name='doc_type',
        ),
    ]
