# Generated by Django 3.2.3 on 2021-07-12 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_rename_new_doc_type_documents_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='doc_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doc_type_docs', to='document.documenttype'),
        ),
    ]
