# Generated by Django 3.2.3 on 2021-07-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_alter_documents_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
