# Generated by Django 3.2.3 on 2021-08-23 18:08

from django.db import migrations, models
import keel.document.utils


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0028_alter_documents_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('avatar', models.FileField(blank=True, upload_to=keel.document.utils.upload_files_to, verbose_name='PublicDocuments')),
                ('original_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
