# Generated by Django 3.2.3 on 2021-08-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0029_publicdocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicdocuments',
            name='avatar',
            field=models.FileField(blank=True, upload_to='', verbose_name='PublicDocuments'),
        ),
    ]
