# Generated by Django 3.2.3 on 2023-03-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0036_alter_documents_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='verification_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PENDING'), (2, 'REJECTED'), (3, 'APPROVED')], default=1),
        ),
    ]
