# Generated by Django 3.2.3 on 2021-11-24 09:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaire', '0006_auto_20211124_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsweredQuestionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('answer', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Answered Question',
                'verbose_name_plural': 'Answered Questions',
                'db_table': 'keel_answered_questions',
            },
        ),
        migrations.CreateModel(
            name='CheckBoxModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('checkbox_text', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DropDownModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dropdown_text', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='booleananswermodel',
            name='question',
        ),
        migrations.RemoveField(
            model_name='multiplechoiceanswermodel',
            name='multiple_choice_answer',
        ),
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(default=datetime.datetime(2021, 11, 24, 9, 38, 45, 400547, tzinfo=utc), help_text='The question text.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[(1, 'Text'), (2, 'Checkbox'), (3, 'Dropdown')], help_text='The answer type.', max_length=1),
        ),
        migrations.DeleteModel(
            name='AnsweredQuestionnaires',
        ),
        migrations.DeleteModel(
            name='BooleanAnswerModel',
        ),
        migrations.DeleteModel(
            name='MultipleChoiceAnswerModel',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.AddField(
            model_name='dropdownmodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_dropdown', to='questionnaire.question'),
        ),
        migrations.AddField(
            model_name='checkboxmodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_checkbox', to='questionnaire.question'),
        ),
        migrations.AddField(
            model_name='answeredquestionsmodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_answered', to='questionnaire.question'),
        ),
        migrations.AddField(
            model_name='answeredquestionsmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_answered_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
