# Generated by Django 3.2.3 on 2021-12-09 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaire', '0010_question_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeredquestionsmodel',
            name='question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_answered', to='questionnaire.question'),
        ),
        migrations.AlterField(
            model_name='answeredquestionsmodel',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_answered_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
