# Generated by Django 3.2.3 on 2021-12-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_auto_20211209_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeredquestionsmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='answeredquestionsmodel',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
