# Generated by Django 3.2.3 on 2021-12-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_auto_20211214_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpouseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('question_text', models.TextField(help_text='The question text.')),
                ('answer_type', models.PositiveSmallIntegerField(choices=[(1, 'Text'), (2, 'Checkbox'), (3, 'Dropdown')], help_text='The answer type.')),
                ('is_active', models.BooleanField(default=True, help_text='Is the question active?')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
