# Generated by Django 3.2.3 on 2021-12-15 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_spousequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkboxmodel',
            name='spouse_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spouse_question_checkbox', to='questionnaire.spousequestion'),
        ),
        migrations.AddField(
            model_name='dropdownmodel',
            name='spouse_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spouse_question_dropdown', to='questionnaire.spousequestion'),
        ),
    ]
