# Generated by Django 3.2.3 on 2021-12-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0014_auto_20211215_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='key',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='spousequestion',
            name='key',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
