# Generated by Django 3.2.3 on 2021-12-27 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0015_auto_20211220_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkboxmodel',
            name='score',
            field=models.BigIntegerField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dropdownmodel',
            name='score',
            field=models.BigIntegerField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='QuestionnaireAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('uuid', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_analysis', to='questionnaire.question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
