# Generated by Django 3.2.3 on 2021-12-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0017_auto_20211227_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkboxmodel',
            old_name='score',
            new_name='with_spouse_score',
        ),
        migrations.RenameField(
            model_name='dropdownmodel',
            old_name='score',
            new_name='with_spouse_score',
        ),
        migrations.AddField(
            model_name='checkboxmodel',
            name='without_spouse_score',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dropdownmodel',
            name='without_spouse_score',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
