# Generated by Django 3.2.3 on 2022-01-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0018_auto_20211228_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkboxmodel',
            name='with_spouse_score',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='checkboxmodel',
            name='without_spouse_score',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dropdownmodel',
            name='with_spouse_score',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dropdownmodel',
            name='without_spouse_score',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
