# Generated by Django 3.2.3 on 2022-02-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0020_question_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='index',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
