# Generated by Django 3.2.3 on 2022-02-24 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0021_alter_question_index'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='checkboxmodel',
        #     name='dependent_question',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dependent_question_checkbox', to='questionnaire.question'),
        # ),
        # migrations.AddField(
        #     model_name='dropdownmodel',
        #     name='dependent_question',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dependent_question_dropdown', to='questionnaire.question'),
        # ),
    ]
