# Generated by Django 3.2.3 on 2022-03-01 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0022_auto_20220224_2040'),
        ('questionnaire', '0022_auto_20220228_1303'),
    ]

    operations = [
    ]
