# Generated by Django 3.2.3 on 2022-03-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0023_merge_0022_auto_20220224_2040_0022_auto_20220228_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='index',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
