# Generated by Django 3.2.3 on 2021-05-26 18:07

from django.db import migrations
import keel.authentication.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', keel.authentication.models.CustomUserManager()),
            ],
        ),
    ]
