# Generated by Django 3.2.3 on 2021-06-18 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_token_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='CustomToken',
        ),
    ]
