# Generated by Django 3.2.3 on 2021-06-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userdocument'),
        ('authentication', '0008_auto_20210621_1621'),
    ]

    operations = [
    ]
