# Generated by Django 3.2.3 on 2021-06-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='customtoken',
            name='token',
            field=models.CharField(default=None, max_length=512, null=True),
        ),
    ]
