# Generated by Django 3.2.3 on 2021-06-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_merge_0004_userdocument_0008_auto_20210621_1621'),
        ('authentication', '0010_auto_20210624_1831'),
    ]

    operations = [
    ]