# Generated by Django 3.2.3 on 2021-07-07 20:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 20, 32, 49, 440311, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CUSTOMER'), (2, 'RCIC')], default=1, null=True, verbose_name='User Types'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='reset_token',
            field=models.CharField(blank=True, default=None, max_length=512, null=True, unique=True),
        ),
    ]
