# Generated by Django 3.2.3 on 2021-06-29 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 2, 0, 27, 291759)),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='reset_token',
            field=models.CharField(blank=True, default=None, max_length=512, null=True, unique=True),
        ),
    ]
