# Generated by Django 3.2.3 on 2021-07-07 20:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20210708_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 20, 33, 39, 335552, tzinfo=utc)),
        ),
    ]
