# Generated by Django 3.2.3 on 2021-07-02 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_passwordresettoken_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 19, 52, 7, 687337)),
        ),
    ]
