# Generated by Django 3.2.3 on 2021-07-06 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_auto_20210706_1558'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='user',
        #     name='id',
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='uuid',
        #     field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        # ),
        # migrations.AlterField(
        #     model_name='passwordresettoken',
        #     name='expiry_date',
        #     field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 16, 10, 0, 947219, tzinfo=utc)),
        # ),
    ]
