# Generated by Django 3.2.3 on 2021-07-07 07:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_auto_20210707_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 8, 2, 18, 73386, tzinfo=utc)),
        ),
    ]
