# Generated by Django 3.2.3 on 2021-07-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_auto_20210713_1443'),
        ('authentication', '0024_userservice'),
    ]

    operations = [
    ]
