# Generated by Django 3.2.3 on 2021-07-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_merge_0024_auto_20210713_1443_0024_userservice'),
        ('authentication', '0025_userdocument_task'),
    ]

    operations = [
    ]
