# Generated by Django 3.2.3 on 2021-07-20 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_auto_20210720_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerqualifications',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_qualification', to=settings.AUTH_USER_MODEL),
        ),
    ]
