# Generated by Django 3.2.3 on 2021-07-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_auto_20210719_2315'),
        ('authentication', '0031_alter_customerqualifications_user'),
    ]

    operations = [
    ]
