# Generated by Django 3.2.3 on 2021-08-02 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_auto_20210728_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileQualificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.CharField(max_length=512)),
                ('institute', models.CharField(max_length=512)),
                ('year_of_passing', models.CharField(max_length=512)),
                ('city', models.CharField(max_length=512)),
                ('country', models.CharField(max_length=512)),
                ('start_date', models.CharField(max_length=512)),
                ('end_date', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelativeInCanadaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('full_name', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('relationship', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('immigration_status', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('contact_number', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('email_address', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='relative_in_canada', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationalCreationalAssessmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('eca_authority_name', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('eca_authority_number', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('canadian_equivalency_summary', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='educational_creational', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
