# Generated by Django 3.2.3 on 2021-08-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0034_educationalcreationalassessmentmodel_profilequalificationmodel_relativeincanadamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationLabelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('institute_label', models.CharField(max_length=512)),
                ('year_of_passing_label', models.CharField(max_length=512)),
                ('city_label', models.CharField(max_length=512)),
                ('country_label', models.CharField(max_length=512)),
                ('start_date_label', models.CharField(max_length=512)),
                ('end_date_label', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ProfileQualificationModel',
        ),
    ]
