# Generated by Django 3.2.3 on 2021-08-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0035_auto_20210802_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificationlabelmodel',
            name='user_label',
            field=models.CharField(default='user', max_length=512),
        ),
    ]
