# Generated by Django 3.2.3 on 2021-08-02 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0036_qualificationlabelmodel_user_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerqualifications',
            old_name='institute_name',
            new_name='institute',
        ),
    ]
