# Generated by Django 3.2.3 on 2021-08-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0038_auto_20210803_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerworkexperience',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='customerworkexperience',
            name='company_name',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='customerworkexperience',
            name='designation',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='customerworkexperience',
            name='job_description',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='customerworkexperience',
            name='weekly_working_hours',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
