# Generated by Django 3.2.3 on 2021-08-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0039_auto_20210803_1625'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkExperinceLabel',
            new_name='WorkExperienceLabel',
        ),
    ]
