# Generated by Django 3.2.3 on 2021-08-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0040_rename_workexperincelabel_workexperiencelabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfileLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user_label', models.CharField(default='user', max_length=512)),
                ('first_name_label', models.CharField(max_length=512)),
                ('last_name_label', models.CharField(max_length=512)),
                ('mother_fullname_label', models.CharField(max_length=512)),
                ('father_fullname_label', models.CharField(max_length=512)),
                ('age_label', models.CharField(max_length=512)),
                ('address_label', models.CharField(max_length=512)),
                ('date_of_birth_label', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
