# Generated by Django 3.2.3 on 2021-08-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0041_customerprofilelabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalCreationalAssessmentLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user_label', models.CharField(default='user', max_length=215)),
                ('eca_authority_name_label', models.CharField(max_length=215)),
                ('eca_authority_number_label', models.CharField(max_length=215)),
                ('canadian_equivalency_summary_label', models.CharField(max_length=215)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelativeInCanadaLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user_label', models.CharField(default='user', max_length=215)),
                ('full_name_label', models.CharField(max_length=215)),
                ('relationship_label', models.CharField(max_length=215)),
                ('immigrations_status_label', models.CharField(max_length=215)),
                ('address_label', models.CharField(max_length=215)),
                ('contact_number_label', models.CharField(max_length=215)),
                ('email_address_label', models.CharField(max_length=215)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='EducationalCreationalAssessmentModel',
            new_name='EducationalCreationalAssessment',
        ),
        migrations.RenameModel(
            old_name='RelativeInCanadaModel',
            new_name='RelativeInCanada',
        ),
    ]
