# Generated by Django 3.2.3 on 2021-08-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0042_auto_20210804_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofilelabel',
            name='phone_number_label',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
