# Generated by Django 3.2.3 on 2021-08-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0044_qualificationlabel_grade_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='current_country',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='desired_country',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
