# Generated by Django 3.2.3 on 2021-08-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0045_auto_20210812_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerqualifications',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='qualificationlabel',
            name='state_label',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
