# Generated by Django 3.2.3 on 2021-08-16 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0046_auto_20210816_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relativeincanadalabel',
            old_name='immigrations_status_label',
            new_name='immigration_status_label',
        ),
    ]
