# Generated by Django 3.2.3 on 2021-08-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0047_rename_immigrations_status_label_relativeincanadalabel_immigration_status_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofilelabel',
            name='current_country_label',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='customerprofilelabel',
            name='desired_country_label',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
