# Generated by Django 3.2.3 on 2021-08-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0048_auto_20210816_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerqualifications',
            name='degree',
            field=models.CharField(blank=True, choices=[(1, 'BACHELORS'), (2, 'MASTERS')], default=1, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='qualificationlabel',
            name='degree_label',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
