# Generated by Django 3.2.3 on 2021-08-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0052_alter_customerworkexperience_job_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
    ]
