# Generated by Django 3.2.3 on 2021-08-20 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0053_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerqualifications',
            name='degree',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('full_name', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('license', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_profile',
            },
        ),
    ]
