# Generated by Django 3.2.3 on 2021-08-20 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_alter_country_options'),
        ('authentication', '0056_auto_20210820_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerworkexperience',
            name='country',
            field=models.ForeignKey(blank=True, default=None, max_length=512, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='country_customer_experience', to='Core.country'),
        ),
        migrations.AddField(
            model_name='customerworkexperience',
            name='state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='state_customer_experience', to='Core.state'),
        ),
    ]
