# Generated by Django 3.2.3 on 2021-08-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0057_auto_20210820_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperiencelabel',
            name='country_label',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workexperiencelabel',
            name='state_label',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
