# Generated by Django 3.2.3 on 2021-09-03 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0059_alter_customerworkexperience_job_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentprofile',
            old_name='user',
            new_name='agent',
        ),
    ]
