# Generated by Django 3.2.3 on 2021-09-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0053_alter_user_user_type'),
        ('authentication', '0060_rename_user_agentprofile_agent'),
    ]

    operations = [
    ]
