# Generated by Django 3.2.3 on 2021-09-09 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0061_merge_20210908_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountManagerProfile',
            fields=[
                ('agentprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.agentprofile')),
            ],
            options={
                'db_table': 'account_manager_profile',
            },
            bases=('authentication.agentprofile',),
        ),
    ]
