# Generated by Django 3.2.3 on 2021-09-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0062_accountmanagerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='call_default_contact',
            field=models.BooleanField(default=False),
        ),
    ]
