# Generated by Django 3.2.3 on 2022-01-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0065_smsotpmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsotpmodel',
            name='phone_number',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
