# Generated by Django 3.2.3 on 2022-02-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0066_alter_smsotpmodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CUSTOMER'), (2, 'RCIC'), (3, 'ACCOUNT_MANAGER'), (4, 'STAFF')], default=1, null=True, verbose_name='User Types'),
        ),
    ]
