# Generated by Django 3.2.3 on 2022-08-02 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_alter_triggeredemails_email'),
        ('authentication', '0069_alter_customerprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='passport_country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='passport_country_profile', to='Core.country'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='customerprofilelabel',
            name='passport_country_label',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customerprofilelabel',
            name='passport_expiry_date_label',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customerprofilelabel',
            name='passport_issue_date_label',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customerprofilelabel',
            name='passport_number_label',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
