# Generated by Django 3.2.3 on 2022-08-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0070_auto_20220802_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalcreationalassessment',
            name='eca_date',
            field=models.DateField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='educationalcreationalassessmentlabel',
            name='eca_date_label',
            field=models.CharField(blank=True, max_length=215, null=True),
        ),
    ]
