# Generated by Django 3.2.3 on 2022-08-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0072_customerlanguagescore_customerlanguagescorelabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='type_of_visa',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Study'), (2, 'PGWP'), (3, 'WorkPermit'), (4, 'PR'), (5, 'Dependant'), (6, 'Visit'), (7, 'Citizenship')], null=True),
        ),
        migrations.AddField(
            model_name='customerprofilelabel',
            name='type_of_visa_label',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='customerworkexperience',
            name='job_description',
            field=models.CharField(blank=True, default=None, max_length=4096, null=True),
        ),
    ]
