# Generated by Django 3.2.3 on 2022-09-12 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_alter_triggeredemails_email'),
        ('authentication', '0073_auto_20220822_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSpouseProfileLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_label', models.CharField(default='user', max_length=255)),
                ('customer_label', models.CharField(max_length=255)),
                ('first_name_label', models.CharField(max_length=255)),
                ('last_name_label', models.CharField(max_length=255)),
                ('mother_fullname_label', models.CharField(max_length=255)),
                ('father_fullname_label', models.CharField(max_length=255)),
                ('age_label', models.CharField(max_length=255)),
                ('passport_number_label', models.CharField(max_length=255)),
                ('passport_country_label', models.CharField(max_length=255)),
                ('passport_issue_date_label', models.CharField(max_length=255)),
                ('passport_expiry_date_label', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'customer_spouse_profile_label',
            },
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='marital_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Single'), (2, 'Married'), (3, 'Divorced')], null=True),
        ),
        migrations.AddField(
            model_name='customerprofilelabel',
            name='marital_status_label',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.CreateModel(
            name='CustomerSpouseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('mother_fullname', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('father_fullname', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('age', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=512, null=True)),
                ('passport_issue_date', models.DateField(blank=True, null=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_spouse', to='authentication.customerprofile')),
                ('passport_country', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='passport_country_spouse_profile', to='Core.country')),
            ],
            options={
                'db_table': 'customer_spouse_profile',
            },
        ),
    ]
