# Generated by Django 3.2.3 on 2022-09-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0075_auto_20220913_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlanguagescore',
            name='test_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerlanguagescorelabel',
            name='test_date_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='eye_color',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='height',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='customerprofilelabel',
            name='eye_color_label',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customerprofilelabel',
            name='height_label',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
