# Generated by Django 3.2.3 on 2022-09-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0076_auto_20220913_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerlanguagescore',
            name='mother_tongue',
        ),
        migrations.RemoveField(
            model_name='customerlanguagescorelabel',
            name='mother_tongue_label',
        ),
        migrations.AddField(
            model_name='customerlanguagescore',
            name='overall_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerlanguagescorelabel',
            name='overall_score_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='funds_available',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customerprofilelabel',
            name='funds_available_label',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
