# Generated by Django 3.2.3 on 2022-09-20 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_alter_triggeredemails_email'),
        ('authentication', '0077_auto_20220916_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFamilyInformationLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_label', models.CharField(max_length=255)),
                ('user_label', models.CharField(default='user', max_length=255)),
                ('date_of_birth_label', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_death_label', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name_label', models.CharField(max_length=255)),
                ('last_name_label', models.CharField(max_length=255)),
                ('city_of_birth_label', models.CharField(max_length=255)),
                ('country_of_birth_label', models.CharField(max_length=255)),
                ('street_address_label', models.CharField(max_length=255)),
                ('current_country_label', models.CharField(max_length=255)),
                ('current_state_label', models.CharField(max_length=255)),
                ('current_occupation_label', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'customer_family_information_label',
            },
        ),
        migrations.RemoveField(
            model_name='customerspouseprofilelabel',
            name='customer_label',
        ),
        migrations.CreateModel(
            name='CustomerFamilyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.PositiveSmallIntegerField(choices=[(1, 'FATHER'), (2, 'MOTHER'), (3, 'BROTHER'), (4, 'SISTER')])),
                ('first_name', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('date_of_birth', models.DateField(blank=True, default=None, null=True)),
                ('date_of_death', models.DateField(blank=True, default=None, null=True)),
                ('city_of_birth', models.CharField(blank=True, max_length=256, null=True)),
                ('street_address', models.CharField(blank=True, max_length=512, null=True)),
                ('current_occupation', models.CharField(blank=True, max_length=256, null=True)),
                ('country_of_birth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_family_birth_country', to='Core.country')),
                ('current_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_family_current_country', to='Core.country')),
                ('current_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_family_current_state', to='Core.state')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_family', to='authentication.customerprofile')),
            ],
            options={
                'db_table': 'customer_family_information',
            },
        ),
    ]
