# Generated by Django 3.2.3 on 2022-09-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0078_auto_20220920_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfamilyinformation',
            name='current_state',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
