# Generated by Django 3.2.3 on 2022-09-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0079_alter_customerfamilyinformation_current_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='any_previous_marriage',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='previous_marriage',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], null=True),
        ),
    ]
