# Generated by Django 3.2.3 on 2023-01-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0080_auto_20220921_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerworkexperience',
            name='is_current_job',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperiencelabel',
            name='is_current_job_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerlanguagescore',
            name='listening_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='customerlanguagescore',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerlanguagescore',
            name='reading_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='customerlanguagescore',
            name='speaking_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='customerlanguagescore',
            name='writing_score',
            field=models.FloatField(),
        ),
    ]
