# Generated by Django 3.2.3 on 2023-01-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0082_alter_customerfamilyinformation_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfamilyinformation',
            name='relationship',
            field=models.PositiveSmallIntegerField(choices=[(1, 'FATHER'), (2, 'MOTHER'), (3, 'BROTHER'), (4, 'SISTER'), (5, 'DAUGHTER'), (6, 'SON')]),
        ),
    ]
