# Generated by Django 3.2.3 on 2021-09-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callschedule',
            name='call_schedule_client_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Calendly')], default=1),
        ),
    ]
