# Generated by Django 3.2.3 on 2021-07-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='plan_id',
            new_name='plan',
        ),
    ]
