# Generated by Django 3.2.3 on 2021-07-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_rename_plan_id_case_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
