# Generated by Django 3.2.3 on 2021-07-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_rename_plan_id_case_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'BOOKED'), (2, 'IN_PROGRESS'), (3, 'COMPLETED'), (4, 'CANCELLED')], default=1, null=True, verbose_name='case_status'),
        ),
    ]
