# Generated by Django 3.2.3 on 2021-07-19 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0002_auto_20210708_1823'),
        ('cases', '0003_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='agent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agents_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_id',
            field=models.CharField(blank=True, default=None, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='case',
            name='plan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plans_cases', to='plans.plan'),
        ),
        migrations.AlterField(
            model_name='case',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
