# Generated by Django 3.2.3 on 2021-07-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_case_deleted_at'),
        ('cases', '0004_auto_20210720_1352'),
    ]

    operations = [
    ]
