# Generated by Django 3.2.3 on 2021-09-21 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0008_rename_choices_program_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='account_manager_id',
        ),
        migrations.AddField(
            model_name='case',
            name='account_manager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_manager_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
