# Generated by Django 3.2.3 on 2021-10-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_auto_20210921_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('Express Entry', 'EXPRESS_ENTRY'), ('Provincial Nomination', 'PROVINCIAL_NOMINATION'), ('Investors', 'INVESTORS'), ('Family Sponsorship', 'FAMILY_SPONSORSHIP')], default='Express Entry', max_length=512),
        ),
    ]
