# Generated by Django 3.2.3 on 2021-10-12 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0009_auto_20210921_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agents_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
