# Generated by Django 3.2.3 on 2021-10-12 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_alter_case_agent'),
        ('cases', '0010_program_category'),
    ]

    operations = [
    ]
