# Generated by Django 3.2.3 on 2022-01-05 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0011_merge_0010_alter_case_agent_0010_program_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, default=None, null=True)),
                ('agent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent_notes', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent_case_notes', to='cases.case')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
