# Generated by Django 3.2.3 on 2022-02-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_casecheckpoint_casetracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetracker',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PENDING'), (2, 'IN_PROGRESS'), (3, 'COMPLETED')], default=1),
        ),
    ]
