# Generated by Django 3.2.3 on 2022-08-23 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_casetracker_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStatusComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('msg', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='case_status_comments', to='cases.case')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
