# Generated by Django 3.2.3 on 2021-11-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inappnotification',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
