# Generated by Django 3.2.3 on 2022-02-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_inappnotification_text_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inappnotification',
            name='text',
        ),
    ]
