# Generated by Django 3.2.3 on 2022-02-24 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_inappnotification_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inappnotification',
            old_name='text_json',
            new_name='text',
        ),
    ]
